<option value="Afghanistan" <?php selected( $value,'Afghanistan');?> ><?php _e('Afghanistan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Aland Islands" <?php selected( $value,'Aland Islands');?> ><?php _e('Åland Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Albania" <?php selected( $value,'Albania');?> ><?php _e('Albania','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Algeria" <?php selected( $value,'Algeria');?> ><?php _e('Algeria','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="American Samoa" <?php selected( $value,'American Samoa');?> ><?php _e('American Samoa','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Andorra" <?php selected( $value,'Andorra');?> ><?php _e('Andorra','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Angola" <?php selected( $value,'Angola');?> ><?php _e('Angola','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Anguilla" <?php selected( $value,'Anguilla');?> ><?php _e('Anguilla','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica" <?php selected( $value,'Antarctica');?> ><?php _e('Antarctica','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antigua and Barbuda" <?php selected( $value,'Antigua and Barbuda');?> ><?php _e('Antigua and Barbuda','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Argentina" <?php selected( $value,'Argentina');?> ><?php _e('Argentina','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Armenia" <?php selected( $value,'Armenia');?> ><?php _e('Armenia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Aruba" <?php selected( $value,'Aruba');?> ><?php _e('Aruba','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia" <?php selected( $value,'Australia');?> ><?php _e('Australia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Austria" <?php selected( $value,'Austria');?> ><?php _e('Austria','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Azerbaijan" <?php selected( $value,'Azerbaijan');?> ><?php _e('Azerbaijan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Bahamas" <?php selected( $value,'Bahamas');?> ><?php _e('Bahamas','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Bahrain" <?php selected( $value,'Bahrain');?> ><?php _e('Bahrain','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Bangladesh" <?php selected( $value,'Bangladesh');?> ><?php _e('Bangladesh','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Barbados" <?php selected( $value,'Barbados');?> ><?php _e('Barbados','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Belarus" <?php selected( $value,'Belarus');?> ><?php _e('Belarus','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Belgium" <?php selected( $value,'Belgium');?> ><?php _e('Belgium','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Belize" <?php selected( $value,'Belize');?> ><?php _e('Belize','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Benin" <?php selected( $value,'Benin');?> ><?php _e('Benin','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Bermuda" <?php selected( $value,'Bermuda');?> ><?php _e('Bermuda','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Bhutan" <?php selected( $value,'Bhutan');?> ><?php _e('Bhutan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Bolivia" <?php selected( $value,'Bolivia');?> ><?php _e('Bolivia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Bosnia and Herzegovina" <?php selected( $value,'Bosnia and Herzegovina');?> ><?php _e('Bosnia and Herzegovina','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Botswana" <?php selected( $value,'Botswana');?> ><?php _e('Botswana','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Bouvet Island" <?php selected( $value,'Bouvet Island');?> ><?php _e('Bouvet Island','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Brazil" <?php selected( $value,'Brazil');?> ><?php _e('Brazil','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="British Indian Ocean Territory" <?php selected( $value,'British Indian Ocean Territory');?> ><?php _e('British Indian Ocean Territory','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Brunei Darussalam" <?php selected( $value,'Brunei Darussalam');?> ><?php _e('Brunei Darussalam','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Bulgaria" <?php selected( $value,'Bulgaria');?> ><?php _e('Bulgaria','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Burkina Faso" <?php selected( $value,'Burkina Faso');?> ><?php _e('Burkina Faso','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Burundi" <?php selected( $value,'Burundi');?> ><?php _e('Burundi','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Cambodia" <?php selected( $value,'Cambodia');?> ><?php _e('Cambodia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Cameroon" <?php selected( $value,'Cameroon');?> ><?php _e('Cameroon','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Canada" <?php selected( $value,'Canada');?> ><?php _e('Canada','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Cape Verde" <?php selected( $value,'Cape Verde');?> ><?php _e('Cape Verde','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Cayman Islands" <?php selected( $value,'Cayman Islands');?> ><?php _e('Cayman Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Central African Republic" <?php selected( $value,'Central African Republic');?> ><?php _e('Central African Republic','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Chad" <?php selected( $value,'Chad');?> ><?php _e('Chad','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Chile" <?php selected( $value,'Chile');?> ><?php _e('Chile','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="China" <?php selected( $value,'China');?> ><?php _e('China','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Christmas Island" <?php selected( $value,'Christmas Island');?> ><?php _e('Christmas Island','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Cocos (Keeling) Islands" <?php selected( $value,'Cocos (Keeling) Islands');?> ><?php _e('Cocos (Keeling) Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Colombia" <?php selected( $value,'Colombia');?> ><?php _e('Colombia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Comoros" <?php selected( $value,'Comoros');?> ><?php _e('Comoros','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Congo" <?php selected( $value,'Congo');?> ><?php _e('Congo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Congo, The Democratic Republic of The" <?php selected( $value,'Congo, The Democratic Republic of The');?> ><?php _e('Congo, The Democratic Republic of The','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Cook Islands" <?php selected( $value,'Cook Islands');?> ><?php _e('Cook Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Costa Rica" <?php selected( $value,'Costa Rica');?> ><?php _e('Costa Rica','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Cote D'ivoire" <?php selected( $value,'Cote D ivoire');?> ><?php _e('Cote D ivoire','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Croatia" <?php selected( $value,'Croatia');?> ><?php _e('Croatia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Cuba" <?php selected( $value,'Cuba');?> ><?php _e('Cuba','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Cyprus" <?php selected( $value,'Cyprus');?> ><?php _e('Cyprus','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Czech Republic" <?php selected( $value,'Czech Republic');?> ><?php _e('Czech Republic','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Denmark" <?php selected( $value,'Denmark');?> ><?php _e('Denmark','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Djibouti" <?php selected( $value,'Djibouti');?> ><?php _e('Djibouti','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Dominica" <?php selected( $value,'Dominica');?> ><?php _e('Dominica','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Dominican Republic" <?php selected( $value,'Dominican Republic');?> ><?php _e('Dominican Republic','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Ecuador" <?php selected( $value,'Ecuador');?> ><?php _e('Ecuador','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Egypt" <?php selected( $value,'Egypt');?> ><?php _e('Egypt','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="El Salvador" <?php selected( $value,'El Salvador');?> ><?php _e('El Salvador','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Equatorial Guinea" <?php selected( $value,'Equatorial Guinea');?> ><?php _e('Equatorial Guinea','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Eritrea" <?php selected( $value,'Eritrea');?> ><?php _e('Eritrea','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Estonia" <?php selected( $value,'Estonia');?> ><?php _e('Estonia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Ethiopia" <?php selected( $value,'Ethiopia');?> ><?php _e('Ethiopia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Falkland Islands (Malvinas)" <?php selected( $value,'Falkland Islands (Malvinas)');?> ><?php _e('Falkland Islands (Malvinas)','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Faroe Islands" <?php selected( $value,'Faroe Islands');?> ><?php _e('Faroe Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Fiji" <?php selected( $value,'Fiji');?> ><?php _e('Fiji','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Finland" <?php selected( $value,'Finland');?> ><?php _e('Finland','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="France" <?php selected( $value,'France');?> ><?php _e('France','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="French Guiana" <?php selected( $value,'French Guiana');?> ><?php _e('French Guiana','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="French Polynesia" <?php selected( $value,'French Polynesia');?> ><?php _e('French Polynesia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="French Southern Territories" <?php selected( $value,'French Southern Territories');?> ><?php _e('French Southern Territories','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Gabon" <?php selected( $value,'Gabon');?> ><?php _e('Gabon','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Gambia" <?php selected( $value,'Gambia');?> ><?php _e('Gambia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Georgia" <?php selected( $value,'Georgia');?> ><?php _e('Georgia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Germany" <?php selected( $value,'Germany');?> ><?php _e('Germany','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Ghana" <?php selected( $value,'Ghana');?> ><?php _e('Ghana','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Gibraltar" <?php selected( $value,'Gibraltar');?> ><?php _e('Gibraltar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Greece" <?php selected( $value,'Greece');?> ><?php _e('Greece','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Greenland" <?php selected( $value,'Greenland');?> ><?php _e('Greenland','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Grenada" <?php selected( $value,'Grenada');?> ><?php _e('Grenada','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Guadeloupe" <?php selected( $value,'Guadeloupe');?> ><?php _e('Guadeloupe','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Guam" <?php selected( $value,'Guam');?> ><?php _e('Guam','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Guatemala" <?php selected( $value,'Guatemala');?> ><?php _e('Guatemala','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Guernsey" <?php selected( $value,'Guernsey');?> ><?php _e('Guernsey','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Guinea" <?php selected( $value,'Guinea');?> ><?php _e('Guinea','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Guinea-bissau" <?php selected( $value,'Guinea');?> ><?php _e('Guinea-bissau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Guyana" <?php selected( $value,'Guyana');?> ><?php _e('Guyana','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Haiti" <?php selected( $value,'Haiti');?> ><?php _e('Haiti','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Heard Island and Mcdonald Islands" <?php selected( $value,'Heard Island and Mcdonald Islands');?> ><?php _e('Heard Island and Mcdonald Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Holy See (Vatican City State)" <?php selected( $value,'Holy See (Vatican City State)');?> ><?php _e('Holy See (Vatican City State)','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Honduras" <?php selected( $value,'Honduras');?> ><?php _e('Honduras','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Hong Kong" <?php selected( $value,'Hong Kong');?> ><?php _e('Hong Kong','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Hungary" <?php selected( $value,'Hungary');?> ><?php _e('Hungary','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Iceland" <?php selected( $value,'Iceland');?> ><?php _e('Iceland','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="India" <?php selected( $value,'India');?> ><?php _e('India','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indonesia" <?php selected( $value,'Indonesia');?> ><?php _e('Indonesia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Iran, Islamic Republic of" <?php selected( $value,'Iran, Islamic Republic of');?> ><?php _e('Iran, Islamic Republic of','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Iraq" <?php selected( $value,'Iraq');?> ><?php _e('Iraq','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Ireland" <?php selected( $value,'Ireland');?> ><?php _e('Ireland','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Isle of Man" <?php selected( $value,'Isle of Man');?> ><?php _e('Isle of Man','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Israel" <?php selected( $value,'Israel');?> ><?php _e('Israel','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Italy" <?php selected( $value,'Italy');?> ><?php _e('Italy','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Jamaica" <?php selected( $value,'Jamaica');?> ><?php _e('Jamaica','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Japan" <?php selected( $value,'Japan');?> ><?php _e('Japan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Jersey" <?php selected( $value,'Jersey');?> ><?php _e('Jersey','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Jordan" <?php selected( $value,'Jordan');?> ><?php _e('Jordan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Kazakhstan" <?php selected( $value,'Kazakhstan');?> ><?php _e('Kazakhstan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Kenya" <?php selected( $value,'Kenya');?> ><?php _e('Kenya','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Kiribati" <?php selected( $value,'Kiribati');?> ><?php _e('Kiribati','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Korea, Democratic People's Republic of" <?php selected( $value,"Korea, Democratic People's Republic of");?> ><?php _e("Korea, Democratic People's Republic of",'profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Korea, Republic of" <?php selected( $value,'Korea, Republic of');?> ><?php _e('Korea, Republic of','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Kuwait" <?php selected( $value,'Kuwait');?> ><?php _e('Kuwait','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Kyrgyzstan" <?php selected( $value,'Kyrgyzstan');?> ><?php _e('Kyrgyzstan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Lao People's Democratic Republic" <?php selected( $value,"Lao People's Democratic Republic");?> ><?php _e("Lao People's Democratic Republic",'profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Latvia" <?php selected( $value,'Latvia');?> ><?php _e('Latvia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Lebanon" <?php selected( $value,'Lebanon');?> ><?php _e('Lebanon','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Lesotho" <?php selected( $value,'Lesotho');?> ><?php _e('Lesotho','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Liberia" <?php selected( $value,'Liberia');?> ><?php _e('Liberia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Libyan Arab Jamahiriya" <?php selected( $value,'Libyan Arab Jamahiriya');?> ><?php _e('Libyan Arab Jamahiriya','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Liechtenstein" <?php selected( $value,'Liechtenstein');?> ><?php _e('Liechtenstein','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Lithuania" <?php selected( $value,'Lithuania');?> ><?php _e('Lithuania','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Luxembourg" <?php selected( $value,'Luxembourg');?> ><?php _e('Luxembourg','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Macao" <?php selected( $value,'Macao');?> ><?php _e('Macao','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Macedonia, The Former Yugoslav Republic of" <?php selected( $value,'Macedonia, The Former Yugoslav Republic of');?> ><?php _e('Macedonia, The Former Yugoslav Republic of','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Madagascar" <?php selected( $value,'Madagascar');?> ><?php _e('Madagascar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Malawi" <?php selected( $value,'Malawi');?> ><?php _e('Malawi','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Malaysia" <?php selected( $value,'Malaysia');?> ><?php _e('Malaysia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Maldives" <?php selected( $value,'Maldives');?> ><?php _e('Maldives','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Mali" <?php selected( $value,'Mali');?> ><?php _e('Mali','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Malta" <?php selected( $value,'Malta');?> ><?php _e('Malta','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Marshall Islands" <?php selected( $value,'Marshall Islands');?> ><?php _e('Marshall Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Martinique" <?php selected( $value,'Martinique');?> ><?php _e('Martinique','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Mauritania" <?php selected( $value,'Mauritania');?> ><?php _e('Mauritania','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Mauritius" <?php selected( $value,'Mauritius');?> ><?php _e('Mauritius','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Mayotte" <?php selected( $value,'Mayotte');?> ><?php _e('Mayotte','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Mexico" <?php selected( $value,'Mexico');?> ><?php _e('Mexico','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Micronesia, Federated States of" <?php selected( $value,'Micronesia, Federated States of');?> ><?php _e('Micronesia, Federated States of','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Moldova, Republic of" <?php selected( $value,'Moldova, Republic of');?> ><?php _e('Moldova, Republic of','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Monaco" <?php selected( $value,'Monaco');?> ><?php _e('Monaco','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Mongolia" <?php selected( $value,'Mongolia');?> ><?php _e('Mongolia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Montenegro" <?php selected( $value,'Montenegro');?> ><?php _e('Montenegro','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Montserrat" <?php selected( $value,'Montserrat');?> ><?php _e('Montserrat','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Morocco" <?php selected( $value,'Morocco');?> ><?php _e('Morocco','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Mozambique" <?php selected( $value,'Mozambique');?> ><?php _e('Mozambique','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Myanmar" <?php selected( $value,'Myanmar');?> ><?php _e('Myanmar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Namibia" <?php selected( $value,'Namibia');?> ><?php _e('Namibia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Nauru" <?php selected( $value,'Nauru');?> ><?php _e('Nauru','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Nepal" <?php selected( $value,'Nepal');?> ><?php _e('Nepal','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Netherlands" <?php selected( $value,'Netherlands');?> ><?php _e('Netherlands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Netherlands Antilles" <?php selected( $value,'Netherlands Antilles');?> ><?php _e('Netherlands Antilles','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="New Caledonia" <?php selected( $value,'New Caledonia');?> ><?php _e('New Caledonia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="New Zealand" <?php selected( $value,'New Zealand');?> ><?php _e('New Zealand','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Nicaragua" <?php selected( $value,'Nicaragua');?> ><?php _e('Nicaragua','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Niger" <?php selected( $value,'Niger');?> ><?php _e('Niger','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Nigeria" <?php selected( $value,'Nigeria');?> ><?php _e('Nigeria','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Niue" <?php selected( $value,'Niue');?> ><?php _e('Niue','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Norfolk Island" <?php selected( $value,'Norfolk Island');?> ><?php _e('Norfolk Island','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Northern Mariana Islands" <?php selected( $value,'Northern Mariana Islands');?> ><?php _e('Northern Mariana Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Norway" <?php selected( $value,'Norway');?> ><?php _e('Norway','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Oman" <?php selected( $value,'Oman');?> ><?php _e('Oman','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pakistan" <?php selected( $value,'Pakistan');?> ><?php _e('Pakistan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Palau" <?php selected( $value,'Palau');?> ><?php _e('Palau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Palestinian Territory, Occupied" <?php selected( $value,'Palestinian Territory, Occupied');?> ><?php _e('Palestinian Territory, Occupied','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Panama" <?php selected( $value,'Panama');?> ><?php _e('Panama','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Papua New Guinea" <?php selected( $value,'Papua New Guinea');?> ><?php _e('Papua New Guinea','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Paraguay" <?php selected( $value,'Paraguay');?> ><?php _e('Paraguay','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Peru" <?php selected( $value,'Peru');?> ><?php _e('Peru','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Philippines" <?php selected( $value,'Philippines');?> ><?php _e('Philippines','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pitcairn" <?php selected( $value,'Pitcairn');?> ><?php _e('Pitcairn','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Poland" <?php selected( $value,'Poland');?> ><?php _e('Poland','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Portugal" <?php selected( $value,'Portugal');?> ><?php _e('Portugal','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Puerto Rico" <?php selected( $value,'Puerto Rico');?> ><?php _e('Puerto Rico','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Qatar" <?php selected( $value,'Qatar');?> ><?php _e('Qatar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Reunion" <?php selected( $value,'Reunion');?> ><?php _e('Reunion','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Romania" <?php selected( $value,'Romania');?> ><?php _e('Romania','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Russian Federation" <?php selected( $value,'Russian Federation');?> ><?php _e('Russian Federation','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Rwanda" <?php selected( $value,'Rwanda');?> ><?php _e('Rwanda','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Saint Helena" <?php selected( $value,'Saint Helena');?> ><?php _e('Saint Helena','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Saint Kitts and Nevis" <?php selected( $value,'Saint Kitts and Nevis');?> ><?php _e('Saint Kitts and Nevis','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Saint Lucia" <?php selected( $value,'Saint Lucia');?> ><?php _e('Saint Lucia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Saint Pierre and Miquelon" <?php selected( $value,'Saint Pierre and Miquelon');?> ><?php _e('Saint Pierre and Miquelon','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Saint Vincent and The Grenadines" <?php selected( $value,'Saint Vincent and The Grenadines');?> ><?php _e('Saint Vincent and The Grenadines','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Samoa" <?php selected( $value,'Samoa');?> ><?php _e('Samoa','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="San Marino" <?php selected( $value,'San Marino');?> ><?php _e('San Marino','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Sao Tome and Principe" <?php selected( $value,'Sao Tome and Principe');?> ><?php _e('Sao Tome and Principe','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Saudi Arabia" <?php selected( $value,'Saudi Arabia');?> ><?php _e('Saudi Arabia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Senegal" <?php selected( $value,'Senegal');?> ><?php _e('Senegal','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Serbia" <?php selected( $value,'Serbia');?> ><?php _e('Serbia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Seychelles" <?php selected( $value,'Seychelles');?> ><?php _e('Seychelles','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Sierra Leone" <?php selected( $value,'Sierra Leone');?> ><?php _e('Sierra Leone','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Singapore" <?php selected( $value,'Singapore');?> ><?php _e('Singapore','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Slovakia" <?php selected( $value,'Slovakia');?> ><?php _e('Slovakia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Slovenia" <?php selected( $value,'Slovenia');?> ><?php _e('Slovenia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Solomon Islands" <?php selected( $value,'Solomon Islands');?> ><?php _e('Solomon Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Somalia" <?php selected( $value,'Somalia');?> ><?php _e('Somalia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="South Africa" <?php selected( $value,'South Africa');?> ><?php _e('South Africa','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="South Georgia and The South Sandwich Islands" <?php selected( $value,'South Georgia and The South Sandwich Islands');?> ><?php _e('South Georgia and The South Sandwich Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Spain" <?php selected( $value,'Spain');?> ><?php _e('Spain','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Sri Lanka" <?php selected( $value,'Sri Lanka');?> ><?php _e('Sri Lanka','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Sudan" <?php selected( $value,'Sudan');?> ><?php _e('Sudan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Suriname" <?php selected( $value,'Suriname');?> ><?php _e('Suriname','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Svalbard and Jan Mayen" <?php selected( $value,'Svalbard and Jan Mayen');?> ><?php _e('Svalbard and Jan Mayen','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Swaziland" <?php selected( $value,'Swaziland');?> ><?php _e('Swaziland','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Sweden" <?php selected( $value,'Sweden');?> ><?php _e('Sweden','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Switzerland" <?php selected( $value,'Switzerland');?> ><?php _e('Switzerland','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Syrian Arab Republic" <?php selected( $value,'Syrian Arab Republic');?> ><?php _e('Syrian Arab Republic','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Taiwan, Province of China" <?php selected( $value,'Taiwan, Province of China');?> ><?php _e('Taiwan, Province of China','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Tajikistan" <?php selected( $value,'Tajikistan');?> ><?php _e('Tajikistan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Tanzania, United Republic of" <?php selected( $value,'Tanzania, United Republic of');?> ><?php _e('Tanzania, United Republic of','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Thailand" <?php selected( $value,'Thailand');?> ><?php _e('Thailand','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Timor-leste" <?php selected( $value,'Timor-leste');?> ><?php _e('Timor-leste','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Togo" <?php selected( $value,'Togo');?> ><?php _e('Togo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Tokelau" <?php selected( $value,'Tokelau');?> ><?php _e('Tokelau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Tonga" <?php selected( $value,'Tonga');?> ><?php _e('Tonga','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Trinidad and Tobago" <?php selected( $value,'Trinidad and Tobago');?> ><?php _e('Trinidad and Tobago','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Tunisia" <?php selected( $value,'Tunisia');?> ><?php _e('Tunisia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Turkey" <?php selected( $value,'Turkey');?> ><?php _e('Turkey','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Turkmenistan" <?php selected( $value,'Turkmenistan');?> ><?php _e('Turkmenistan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Turks and Caicos Islands" <?php selected( $value,'Turks and Caicos Islands');?> ><?php _e('Turks and Caicos Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Tuvalu" <?php selected( $value,'Tuvalu');?> ><?php _e('Tuvalu','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Uganda" <?php selected( $value,'Uganda');?> ><?php _e('Uganda','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Ukraine" <?php selected( $value,'Ukraine');?> ><?php _e('Ukraine','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="United Arab Emirates" <?php selected( $value,'United Arab Emirates');?> ><?php _e('United Arab Emirates','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="United Kingdom" <?php selected( $value,'United Kingdom');?> ><?php _e('United Kingdom','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="United States" <?php selected( $value,'United States');?>><?php _e('United States','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="United States Minor Outlying Islands" <?php selected( $value,'United States Minor Outlying Islands');?> ><?php _e('United States Minor Outlying Islands','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Uruguay" <?php selected( $value,'Uruguay');?> ><?php _e('Uruguay','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Uzbekistan" <?php selected( $value,'Uzbekistan');?> ><?php _e('Uzbekistan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Vanuatu" <?php selected( $value,'Vanuatu');?> ><?php _e('Vanuatu','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Venezuela" <?php selected( $value,'Venezuela');?> ><?php _e('Venezuela','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Viet Nam" <?php selected( $value,'Viet Nam');?> ><?php _e('Viet Nam','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Virgin Islands, British" <?php selected( $value,'Virgin Islands, British');?> ><?php _e('Virgin Islands, British','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Virgin Islands, U.S." <?php selected( $value,'Virgin Islands, U.S.');?> ><?php _e('Virgin Islands, U.S.','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Wallis and Futuna" <?php selected( $value,'Wallis and Futuna');?> ><?php _e('Wallis and Futuna','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Western Sahara" <?php selected( $value,'Western Sahara');?> ><?php _e('Western Sahara','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Yemen" <?php selected( $value,'Yemen');?> ><?php _e('Yemen','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Zambia" <?php selected( $value,'Zambia');?> ><?php _e('Zambia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Zimbabwe" <?php selected( $value,'Zimbabwe');?> ><?php _e('Zimbabwe','profilegrid-user-profiles-groups-and-communities');?></option>