<optgroup label="Africa" >
<option value="Africa/Abidjan" <?php selected( $value,'Africa/Abidjan');?> ><?php _e('Africa/Abidjan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Accra" <?php selected( $value,'Africa/Accra');?> ><?php _e('Accra','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Addis_Ababa" <?php selected( $value,'Africa/Addis_Ababa');?> ><?php _e('Addis_Ababa','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Algiers" <?php selected( $value,'Africa/Algiers');?> ><?php _e('Algiers','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Asmara" <?php selected( $value,'Africa/Asmara');?> ><?php _e('Asmara','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Bamako" <?php selected( $value,'Africa/Bamako');?> ><?php _e('Bamako','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Bangui" <?php selected( $value,'Africa/Bangui');?> ><?php _e('Bangui','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Banjul" <?php selected( $value,'Africa/Banjul');?> ><?php _e('Banjul','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Bissau" <?php selected( $value,'Africa/Bissau');?> ><?php _e('Bissau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Blantyre" <?php selected( $value,'Africa/Blantyre');?> ><?php _e('Blantyre','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Brazzaville" <?php selected( $value,'Africa/Brazzaville');?> ><?php _e('Brazzaville','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Bujumbura" <?php selected( $value,'Africa/Bujumbura');?> ><?php _e('Bujumbura','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Cairo" <?php selected( $value,'Africa/Cairo');?> ><?php _e('Cairo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Casablanca" <?php selected( $value,'Africa/Casablanca');?> ><?php _e('Casablanca','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Ceuta" <?php selected( $value,'Africa/Ceuta');?> ><?php _e('Ceuta','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Conakry" <?php selected( $value,'Africa/Conakry');?> ><?php _e('Conakry','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Dakar" <?php selected( $value,'Africa/Dakar');?> ><?php _e('Dakar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Dar_es_Salaam" <?php selected( $value,'Africa/Dar_es_Salaam');?> ><?php _e('Dar_es_Salaam','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Djibouti" <?php selected( $value,'Africa/Djibouti');?> ><?php _e('Djibouti','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Douala" <?php selected( $value,'Africa/Douala');?> ><?php _e('Douala','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/El_Aaiun" <?php selected( $value,'Africa/El_Aaiun');?> ><?php _e('El_Aaiun','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Freetown" <?php selected( $value,'Africa/Freetown');?> ><?php _e('Freetown','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Gaborone" <?php selected( $value,'Africa/Gaborone');?> ><?php _e('Gaborone','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Harare" <?php selected( $value,'Africa/Harare');?> ><?php _e('Harare','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Johannesburg" <?php selected( $value,'Africa/Johannesburg');?> ><?php _e('Johannesburg','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Juba" <?php selected( $value,'Africa/Juba');?> ><?php _e('Juba','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Kampala" <?php selected( $value,'Africa/Kampala');?> ><?php _e('Kampala','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Khartoum" <?php selected( $value,'Africa/Khartoum');?> ><?php _e('Khartoum','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Kigali" <?php selected( $value,'Africa/Kigali');?> ><?php _e('Kigali','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Kinshasa" <?php selected( $value,'Africa/Kinshasa');?> ><?php _e('Kinshasa','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Lagos" <?php selected( $value,'Africa/Lagos');?> ><?php _e('Lagos','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Libreville" <?php selected( $value,'Africa/Libreville');?> ><?php _e('Libreville','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Lome" <?php selected( $value,'Africa/Lome');?> ><?php _e('Lome','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Luanda" <?php selected( $value,'Africa/Luanda');?> ><?php _e('Luanda','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Lubumbashi" <?php selected( $value,'Africa/Lubumbashi');?> ><?php _e('Lubumbashi','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Lusaka" <?php selected( $value,'Africa/Lusaka');?> ><?php _e('Lusaka','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Malabo" <?php selected( $value,'Africa/Malabo');?> ><?php _e('Malabo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Maputo" <?php selected( $value,'Africa/Maputo');?> ><?php _e('Maputo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Maseru" <?php selected( $value,'Africa/Maseru');?> ><?php _e('Maseru','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Mbabane" <?php selected( $value,'Africa/Mbabane');?> ><?php _e('Mbabane','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Mogadishu" <?php selected( $value,'Africa/Mogadishu');?> ><?php _e('Mogadishu','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Monrovia" <?php selected( $value,'Africa/Monrovia');?> ><?php _e('Monrovia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Nairobi" <?php selected( $value,'Africa/Nairobi');?> ><?php _e('Nairobi','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Ndjamena" <?php selected( $value,'Africa/Ndjamena');?> ><?php _e('Ndjamena','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Niamey" <?php selected( $value,'Africa/Niamey');?> ><?php _e('Niamey','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Nouakchott" <?php selected( $value,'Africa/Nouakchott');?> ><?php _e('Nouakchott','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Ouagadougou" <?php selected( $value,'Africa/Ouagadougou');?> ><?php _e('Ouagadougou','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Porto-Novo" <?php selected( $value,'Africa/Porto-Novo');?> ><?php _e('Porto-Novo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Sao_Tome" <?php selected( $value,'Africa/Sao_Tome');?> ><?php _e('Sao_Tome','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Tripoli" <?php selected( $value,'Africa/Tripoli');?> ><?php _e('Tripoli','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Tunis" <?php selected( $value,'Africa/Tunis');?> ><?php _e('Tunis','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Africa/Windhoek" <?php selected( $value,'Africa/Windhoek');?> ><?php _e('Windhoek','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="America">
<option value="America/Adak" <?php selected( $value,'America/Adak');?> ><?php _e('Adak','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Anchorage" <?php selected( $value,'America/Anchorage');?> ><?php _e('Anchorage','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Anguilla" <?php selected( $value,'America/Anguilla');?> ><?php _e('Anguilla','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Antigua" <?php selected( $value,'America/Antigua');?> ><?php _e('Antigua','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Araguaina" <?php selected( $value,'America/Araguaina');?> ><?php _e('Araguaina','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/Buenos_Aires" <?php selected( $value,'America/Argentina - Buenos Aires');?> ><?php _e('Argentina - Buenos Aires','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/Catamarca" <?php selected( $value,'America/Argentina - Catamarca');?> ><?php _e('Argentina - Catamarca','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/Cordoba" <?php selected( $value,'America/Argentina - Cordoba');?> ><?php _e('Argentina - Cordoba','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/Jujuy" <?php selected( $value,'America/Argentina - Jujuy');?> ><?php _e('Argentina - Jujuy','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/La_Rioja" <?php selected( $value,'America/Argentina - La Rioja');?> ><?php _e('Argentina - La Rioja','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/Mendoza" <?php selected( $value,'America/Argentina - Mendoza');?> ><?php _e('Argentina - Mendoza','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/Rio_Gallegos" <?php selected( $value,'America/Argentina - Rio Gallegos');?> ><?php _e('Argentina - Rio Gallegos','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/Salta" <?php selected( $value,'America/Argentina - Salta');?> ><?php _e('Argentina - Salta','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/San_Juan" <?php selected( $value,'America/Argentina - San Juan');?> ><?php _e('Argentina - San Juan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/San_Luis" <?php selected( $value,'America/Argentina - San Luis');?> ><?php _e('Argentina - San Luis','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/Tucuman" <?php selected( $value,'America/Argentina - Tucuman');?> ><?php _e('Argentina - Tucuman','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Argentina/Ushuaia" <?php selected( $value,'America/Argentina - Ushuaia');?> ><?php _e('Argentina - Ushuaia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Aruba" <?php selected( $value,'America/Aruba');?> ><?php _e('Aruba','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Asuncion" <?php selected( $value,'America/Asuncion');?> ><?php _e('Asuncion','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Atikokan" <?php selected( $value,'America/Atikokan');?> ><?php _e('Atikokan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Bahia" <?php selected( $value,'America/Bahia');?> ><?php _e('Bahia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Bahia_Banderas" <?php selected( $value,'America/Bahia Banderas');?> ><?php _e('Bahia Banderas','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Barbados" <?php selected( $value,'America/Barbados');?> ><?php _e('Barbados','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Belem" <?php selected( $value,'America/Belem');?> ><?php _e('Belem','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Belize" <?php selected( $value,'America/Belize');?> ><?php _e('Belize','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Blanc-Sablon" <?php selected( $value,'America/Blanc-Sablon');?> ><?php _e('Blanc-Sablon','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Boa_Vista" <?php selected( $value,'America/Boa Vista');?> ><?php _e('Boa Vista','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Bogota" <?php selected( $value,'America/Bogota');?> ><?php _e('Bogota','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Boise" <?php selected( $value,'America/Boise');?> ><?php _e('Boise','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Cambridge_Bay" <?php selected( $value,'America/Cambridge Bay');?> ><?php _e('Cambridge Bay','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Campo_Grande" <?php selected( $value,'America/Campo Grande');?> ><?php _e('Campo Grande','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Cancun" <?php selected( $value,'America/Cancun');?> ><?php _e('Cancun','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Caracas" <?php selected( $value,'America/Caracas');?> ><?php _e('Caracas','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Cayenne" <?php selected( $value,'America/Cayenne');?> ><?php _e('Cayenne','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Cayman" <?php selected( $value,'America/Cayman');?> ><?php _e('Cayman','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Chicago" <?php selected( $value,'America/Chicago');?> ><?php _e('Chicago','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Chihuahua" <?php selected( $value,'America/Chihuahua');?> ><?php _e('Chihuahua','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Costa_Rica" <?php selected( $value,'America/Costa Rica');?> ><?php _e('Costa Rica','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Creston" <?php selected( $value,'America/Creston');?> ><?php _e('Creston','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Cuiaba" <?php selected( $value,'America/Cuiaba');?> ><?php _e('Cuiaba','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Curacao" <?php selected( $value,'America/Curacao');?> ><?php _e('Curacao','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Danmarkshavn" <?php selected( $value,'America/Danmarkshavn');?> ><?php _e('Danmarkshavn','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Dawson" <?php selected( $value,'America/Dawson');?> ><?php _e('Dawson','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Dawson_Creek" <?php selected( $value,'America/Dawson Creek');?> ><?php _e('Dawson Creek','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Denver" <?php selected( $value,'America/Denver');?> ><?php _e('Denver','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Detroit" <?php selected( $value,'America/Detroit');?> ><?php _e('Detroit','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Dominica" <?php selected( $value,'America/Dominica');?> ><?php _e('Dominica','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Edmonton" <?php selected( $value,'America/Edmonton');?> ><?php _e('Edmonton','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Eirunepe" <?php selected( $value,'America/Eirunepe');?> ><?php _e('Eirunepe','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/El_Salvador" <?php selected( $value,'America/El Salvador');?> ><?php _e('El Salvador','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Fortaleza" <?php selected( $value,'America/Fortaleza');?> ><?php _e('Fortaleza','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Glace_Bay" <?php selected( $value,'America/Glace Bay');?> ><?php _e('Glace Bay','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Godthab" <?php selected( $value,'America/Godthab');?> ><?php _e('Godthab','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Goose_Bay" <?php selected( $value,'America/Goose Bay');?> ><?php _e('Goose Bay','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Grand_Turk" <?php selected( $value,'America/Grand Turk');?> ><?php _e('Grand Turk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Grenada" <?php selected( $value,'America/Grenada');?> ><?php _e('Grenada','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Guadeloupe" <?php selected( $value,'America/Guadeloupe');?> ><?php _e('Guadeloupe','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Guatemala" <?php selected( $value,'America/Guatemala');?> ><?php _e('Guatemala','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Guayaquil" <?php selected( $value,'America/Guayaquil');?> ><?php _e('Guayaquil','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Guyana" <?php selected( $value,'America/Guyana');?> ><?php _e('Guyana','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Halifax" <?php selected( $value,'America/Halifax');?> ><?php _e('Halifax','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Havana" <?php selected( $value,'America/Havana');?> ><?php _e('Havana','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Hermosillo" <?php selected( $value,'America/Hermosillo');?> ><?php _e('Hermosillo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Indiana/Indianapolis" <?php selected( $value,'America/Indiana - Indianapolis');?> ><?php _e('Indiana - Indianapolis','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Indiana/Knox" <?php selected( $value,'America/Indiana - Knox');?> ><?php _e('Indiana - Knox','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Indiana/Marengo" <?php selected( $value,'America/Indiana - Marengo');?> ><?php _e('Indiana - Marengo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Indiana/Petersburg" <?php selected( $value,'America/Indiana - Petersburg');?> ><?php _e('Indiana - Petersburg','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Indiana/Tell_City" <?php selected( $value,'America/Indiana - Tell City');?> ><?php _e('Indiana - Tell City','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Indiana/Vevay" <?php selected( $value,'America/Indiana - Vevay');?> ><?php _e('Indiana - Vevay','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Indiana/Vincennes" <?php selected( $value,'America/Indiana - Vincennes');?> ><?php _e('Indiana - Vincennes','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Indiana/Winamac" <?php selected( $value,'America/Indiana - Winamac');?> ><?php _e('Indiana - Winamac','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Inuvik" <?php selected( $value,'America/Inuvik');?> ><?php _e('Inuvik','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Iqaluit" <?php selected( $value,'America/Iqaluit');?> ><?php _e('Iqaluit','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Jamaica" <?php selected( $value,'America/Jamaica');?> ><?php _e('Jamaica','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Juneau" <?php selected( $value,'America/Juneau');?> ><?php _e('Juneau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Kentucky/Louisville" <?php selected( $value,'America/Kentucky - Louisville');?> ><?php _e('Kentucky - Louisville','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Kentucky/Monticello" <?php selected( $value,'America/Kentucky - Monticello');?> ><?php _e('Kentucky - Monticello','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Kralendijk" <?php selected( $value,'America/Kralendijk');?> ><?php _e('Kralendijk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/La_Paz" <?php selected( $value,'America/La Paz');?> ><?php _e('La Paz','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Lima" <?php selected( $value,'America/Lima');?> ><?php _e('Lima','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Los_Angeles" <?php selected( $value,'America/Los Angeles');?> ><?php _e('Los Angeles','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Lower_Princes" <?php selected( $value,'America/Lower Princes');?> ><?php _e('Lower Princes','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Maceio" <?php selected( $value,'America/Maceio');?> ><?php _e('Maceio','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Managua" <?php selected( $value,'America/Managua');?> ><?php _e('Managua','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Manaus" <?php selected( $value,'America/Manaus');?> ><?php _e('Manaus','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Marigot" <?php selected( $value,'America/Marigot');?> ><?php _e('Marigot','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Martinique" <?php selected( $value,'America/Martinique');?> ><?php _e('Martinique','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Matamoros" <?php selected( $value,'America/Matamoros');?> ><?php _e('Matamoros','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Mazatlan" <?php selected( $value,'America/Mazatlan');?> ><?php _e('Mazatlan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Menominee" <?php selected( $value,'America/Menominee');?> ><?php _e('Menominee','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Merida" <?php selected( $value,'America/Merida');?> ><?php _e('Merida','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Metlakatla" <?php selected( $value,'America/Metlakatla');?> ><?php _e('Metlakatla','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Mexico_City" <?php selected( $value,'America/Mexico City');?> ><?php _e('Mexico City','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Miquelon" <?php selected( $value,'America/Miquelon');?> ><?php _e('Miquelon','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Moncton" <?php selected( $value,'America/Moncton');?> ><?php _e('Moncton','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Monterrey" <?php selected( $value,'America/Monterrey');?> ><?php _e('Monterrey','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Montevideo" <?php selected( $value,'America/Montevideo');?> ><?php _e('Montevideo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Montserrat" <?php selected( $value,'America/Montserrat');?> ><?php _e('Montserrat','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Nassau" <?php selected( $value,'America/Nassau');?> ><?php _e('Nassau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/New_York" <?php selected( $value,'America/New York');?> ><?php _e('New York','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Nipigon" <?php selected( $value,'America/Nipigon');?> ><?php _e('Nipigon','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Nome" <?php selected( $value,'America/Nome');?> ><?php _e('Nome','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Noronha" <?php selected( $value,'America/Noronha');?> ><?php _e('Noronha','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/North_Dakota/Beulah" <?php selected( $value,'America/Noronha');?> ><?php _e('North Dakota - Beulah','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/North_Dakota/Center" <?php selected( $value,'America/North Dakota - Center');?> ><?php _e('North Dakota - Center','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/North_Dakota/New_Salem" <?php selected( $value,'America/North Dakota - New Salem');?> ><?php _e('North Dakota - New Salem','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Ojinaga" <?php selected( $value,'America/Ojinaga');?> ><?php _e('Ojinaga','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Panama" <?php selected( $value,'Panama');?> ><?php _e('Panama','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Pangnirtung" <?php selected( $value,'America/Pangnirtung');?> ><?php _e('Pangnirtung','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Paramaribo" <?php selected( $value,'America/Paramaribo');?> ><?php _e('Paramaribo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Phoenix" <?php selected( $value,'America/Phoenix');?> ><?php _e('Phoenix','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Port-au-Prince" <?php selected( $value,'America/Port-au-Prince');?> ><?php _e('Port-au-Prince','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Port_of_Spain" <?php selected( $value,'America/Port of Spain');?> ><?php _e('Port of Spain','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Porto_Velho" <?php selected( $value,'America/Porto Velho');?> ><?php _e('Porto Velho','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Puerto_Rico" <?php selected( $value,'America/Puerto Rico');?> ><?php _e('Puerto Rico','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Rainy_River" <?php selected( $value,'America/Rainy River');?> ><?php _e('Rainy River','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Rankin_Inlet" <?php selected( $value,'America/Rankin Inlet');?> ><?php _e('Rankin Inlet','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Recife" <?php selected( $value,'America/Recife');?> ><?php _e('Recife','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Regina" <?php selected( $value,'America/Regina');?> ><?php _e('Regina','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Resolute" <?php selected( $value,'America/Resolute');?> ><?php _e('Resolute','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Rio_Branco" <?php selected( $value,'America/Rio Branco');?> ><?php _e('Rio Branco','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Santa_Isabel" <?php selected( $value,'America/Santa Isabel');?> ><?php _e('Santa Isabel','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Santarem" <?php selected( $value,'America/Santarem');?> ><?php _e('Santarem','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Santiago" <?php selected( $value,'America/Santiago');?> ><?php _e('Santiago','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Santo_Domingo" <?php selected( $value,'America/Santo Domingo');?> ><?php _e('Santo Domingo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Sao_Paulo" <?php selected( $value,'America/Sao Paulo');?> ><?php _e('Sao Paulo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Scoresbysund" <?php selected( $value,'America/Scoresbysund');?> ><?php _e('Scoresbysund','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Sitka" <?php selected( $value,'America/Sitka');?> ><?php _e('Sitka','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/St_Barthelemy" <?php selected( $value,'America/St Barthelemy');?> ><?php _e('St Barthelemy','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/St_Johns" <?php selected( $value,'America/St Johns');?> ><?php _e('St Johns','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/St_Kitts" <?php selected( $value,'America/St Kitts');?> ><?php _e('St Kitts','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/St_Lucia" <?php selected( $value,'America/St Lucia');?> ><?php _e('St Lucia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/St_Thomas" <?php selected( $value,'America/St Thomas');?> ><?php _e('St Thomas','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/St_Vincent" <?php selected( $value,'America/St Vincent');?> ><?php _e('St Vincent','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Swift_Current" <?php selected( $value,'America/Swift Current');?> ><?php _e('Swift Current','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Tegucigalpa" <?php selected( $value,'America/Tegucigalpa');?> ><?php _e('Tegucigalpa','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Thule" <?php selected( $value,'America/Thule');?> ><?php _e('Thule','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Thunder_Bay" <?php selected( $value,'America/Thunder Bay');?> ><?php _e('Thunder Bay','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Tijuana" <?php selected( $value,'America/Tijuana');?> ><?php _e('Tijuana','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Toronto" <?php selected( $value,'America/Toronto');?> ><?php _e('Toronto','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Tortola" <?php selected( $value,'America/Tortola');?> ><?php _e('Tortola','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Vancouver" <?php selected( $value,'America/Vancouver');?> ><?php _e('Vancouver','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Whitehorse" <?php selected( $value,'America/Whitehorse');?> ><?php _e('Whitehorse','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Winnipeg" <?php selected( $value,'America/Winnipeg');?> ><?php _e('Winnipeg','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Yakutat" <?php selected( $value,'America/Yakutat');?> ><?php _e('Yakutat','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="America/Yellowknife" <?php selected( $value,'America/Yellowknife');?> ><?php _e('Yellowknife','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="Antarctica">
<option value="Antarctica/Casey" <?php selected( $value,'Antarctica/Casey');?> ><?php _e('Casey','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/Davis" <?php selected( $value,'Antarctica/Davis');?> ><?php _e('Davis','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/DumontDUrville" <?php selected( $value,'Antarctica/DumontDUrville');?> ><?php _e('DumontDUrville','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/Macquarie" <?php selected( $value,'Antarctica/Macquarie');?> ><?php _e('Macquarie','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/Mawson" <?php selected( $value,'Antarctica/Mawson');?> ><?php _e('Mawson','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/McMurdo" <?php selected( $value,'Antarctica/McMurdo');?> ><?php _e('McMurdo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/Palmer" <?php selected( $value,'Antarctica/Palmer');?> ><?php _e('Palmer','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/Rothera" <?php selected( $value,'Antarctica/Rothera');?> ><?php _e('Rothera','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/Syowa" <?php selected( $value,'Antarctica/Syowa');?> ><?php _e('Syowa','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/Troll" <?php selected( $value,'Antarctica/Troll');?> ><?php _e('Troll','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Antarctica/Vostok" <?php selected( $value,'Antarctica/Vostok');?> ><?php _e('Vostok','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="Arctic" >
<option value="Arctic/Longyearbyen" <?php selected( $value,'Arctic/Longyearbyen');?> ><?php _e('Longyearbyen','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="Asia">
<option value="Asia/Aden" <?php selected( $value,'Asia/Aden');?> ><?php _e('Aden','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Almaty" <?php selected( $value,'Asia/Almaty');?> ><?php _e('Almaty','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Amman" <?php selected( $value,'Asia/Amman');?> ><?php _e('Amman','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Anadyr" <?php selected( $value,'Asia/Anadyr');?> ><?php _e('Anadyr','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Aqtau" <?php selected( $value,'Asia/Aqtau');?> ><?php _e('Aqtau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Aqtobe" <?php selected( $value,'Asia/Aqtobe');?> ><?php _e('Aqtobe','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Ashgabat" <?php selected( $value,'Asia/Ashgabat');?> ><?php _e('Ashgabat','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Baghdad" <?php selected( $value,'Asia/Baghdad');?> ><?php _e('Baghdad','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Bahrain" <?php selected( $value,'Asia/Bahrain');?> ><?php _e('Bahrain','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Baku" <?php selected( $value,'Asia/Baku');?> ><?php _e('Baku','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Bangkok" <?php selected( $value,'Asia/Bangkok');?> ><?php _e('Bangkok','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Beirut" <?php selected( $value,'Asia/Beirut');?> ><?php _e('Beirut','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Bishkek" <?php selected( $value,'Asia/Bishkek');?> ><?php _e('Bishkek','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Brunei" <?php selected( $value,'Asia/Brunei');?> ><?php _e('Brunei','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Choibalsan" <?php selected( $value,'Asia/Choibalsan');?> ><?php _e('Choibalsan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Chongqing" <?php selected( $value,'Asia/Chongqing');?> ><?php _e('Chongqing','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Colombo" <?php selected( $value,'Asia/Colombo');?> ><?php _e('Colombo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Damascus" <?php selected( $value,'Asia/Damascus');?> ><?php _e('Damascus','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Dhaka" <?php selected( $value,'Asia/Dhaka');?> ><?php _e('Dhaka','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Dili" <?php selected( $value,'Asia/Dili');?> ><?php _e('Dili','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Dubai" <?php selected( $value,'Asia/Dubai');?> ><?php _e('Dubai','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Dushanbe" <?php selected( $value,'Asia/Dushanbe');?> ><?php _e('Dushanbe','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Gaza" <?php selected( $value,'Asia/Gaza');?> ><?php _e('Gaza','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Harbin" <?php selected( $value,'Asia/Harbin');?> ><?php _e('Harbin','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Hebron" <?php selected( $value,'Asia/Hebron');?> ><?php _e('Hebron','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Ho_Chi_Minh" <?php selected( $value,'Asia/Ho Chi Minh');?> ><?php _e('Ho Chi Minh','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Hong_Kong" <?php selected( $value,'Asia/Hong Kong');?> ><?php _e('Hong Kong','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Hovd" <?php selected( $value,'Asia/Hovd');?> ><?php _e('Hovd','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Irkutsk" <?php selected( $value,'Asia/Irkutsk');?> ><?php _e('Irkutsk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Jakarta" <?php selected( $value,'Asia/Jakarta');?> ><?php _e('Jakarta','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Jayapura" <?php selected( $value,'Asia/Jayapura');?> ><?php _e('Jayapura','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Jerusalem" <?php selected( $value,'Asia/Jerusalem');?> ><?php _e('Jerusalem','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Kabul" <?php selected( $value,'Asia/Kabul');?> ><?php _e('Kabul','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Kamchatka" <?php selected( $value,'Asia/Kamchatka');?> ><?php _e('Kamchatka','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Karachi" <?php selected( $value,'Asia/Karachi');?> ><?php _e('Karachi','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Kashgar" <?php selected( $value,'Asia/Kashgar');?> ><?php _e('Kashgar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Kathmandu" <?php selected( $value,'Asia/Kathmandu');?> ><?php _e('Kathmandu','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Khandyga" <?php selected( $value,'Asia/Khandyga');?> ><?php _e('Khandyga','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Kolkata" <?php selected( $value,'Asia/Kolkata');?> ><?php _e('Kolkata','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Krasnoyarsk" <?php selected( $value,'Asia/Krasnoyarsk');?> ><?php _e('Krasnoyarsk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Kuala_Lumpur" <?php selected( $value,'Asia/Kuala Lumpur');?> ><?php _e('Kuala Lumpur','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Kuching" <?php selected( $value,'Asia/Kuching');?> ><?php _e('Kuching','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Kuwait" <?php selected( $value,'Asia/Kuwait');?> ><?php _e('Kuwait','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Macau" <?php selected( $value,'Asia/Macau');?> ><?php _e('Macau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Magadan" <?php selected( $value,'Asia/Magadan');?> ><?php _e('Magadan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Makassar" <?php selected( $value,'Asia/Makassar');?> ><?php _e('Makassar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Manila" <?php selected( $value,'Asia/Manila');?> ><?php _e('Manila','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Muscat" <?php selected( $value,'Asia/Muscat');?> ><?php _e('Muscat','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Nicosia" <?php selected( $value,'Asia/Nicosia');?> ><?php _e('Nicosia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Novokuznetsk" <?php selected( $value,'Asia/Novokuznetsk');?> ><?php _e('Novokuznetsk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Novosibirsk" <?php selected( $value,'Asia/Novosibirsk');?> ><?php _e('Novosibirsk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Omsk" <?php selected( $value,'Asia/Omsk');?> ><?php _e('Omsk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Oral" <?php selected( $value,'Asia/Oral');?> ><?php _e('Oral','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Phnom_Penh" <?php selected( $value,'Asia/Phnom Penh');?> ><?php _e('Phnom Penh','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Pontianak" <?php selected( $value,'Asia/Pontianak');?> ><?php _e('Pontianak','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Pyongyang" <?php selected( $value,'Asia/Pyongyang');?> ><?php _e('Pyongyang','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Qatar" <?php selected( $value,'Asia/Qatar');?> ><?php _e('Qatar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Qyzylorda" <?php selected( $value,'Asia/Qyzylorda');?> ><?php _e('Qyzylorda','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Rangoon" <?php selected( $value,'Asia/Rangoon');?> ><?php _e('Rangoon','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Riyadh" <?php selected( $value,'Asia/Riyadh');?> ><?php _e('Riyadh','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Sakhalin" <?php selected( $value,'Asia/Sakhalin');?> ><?php _e('Sakhalin','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Samarkand" <?php selected( $value,'Asia/Samarkand');?> ><?php _e('Samarkand','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Seoul" <?php selected( $value,'Asia/Seoul');?> ><?php _e('Seoul','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Shanghai" <?php selected( $value,'Asia/Shanghai');?> ><?php _e('Shanghai','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Singapore" <?php selected( $value,'Asia/Singapore');?> ><?php _e('Singapore','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Taipei" <?php selected( $value,'Asia/Taipei');?> ><?php _e('Taipei','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Tashkent" <?php selected( $value,'Asia/Tashkent');?> ><?php _e('Tashkent','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Tbilisi" <?php selected( $value,'TAsia/bilisi');?> ><?php _e('Tbilisi','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Tehran" <?php selected( $value,'Asia/Tehran');?> ><?php _e('Tehran','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Thimphu" <?php selected( $value,'Asia/Thimphu');?> ><?php _e('Thimphu','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Tokyo" <?php selected( $value,'Asia/Tokyo');?> ><?php _e('Tokyo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Ulaanbaatar" <?php selected( $value,'Asia/Ulaanbaatar');?> ><?php _e('Ulaanbaatar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Urumqi" <?php selected( $value,'Asia/Urumqi');?> ><?php _e('Urumqi','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Ust-Nera" <?php selected( $value,'Asia/Ust-Nera');?> ><?php _e('Ust-Nera','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Vientiane" <?php selected( $value,'Asia/Vientiane');?> ><?php _e('Vientiane','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Vladivostok" <?php selected( $value,'Asia/Vladivostok');?> ><?php _e('Vladivostok','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Yakutsk" <?php selected( $value,'Asia/Yakutsk');?> ><?php _e('Yakutsk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Yekaterinburg" <?php selected( $value,'Asia/Yekaterinburg');?> ><?php _e('Yekaterinburg','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Asia/Yerevan" <?php selected( $value,'Asia/Yerevan');?> ><?php _e('Yerevan','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="Atlantic" >
<option value="Atlantic/Azores" <?php selected( $value,'Atlantic/Azores');?> ><?php _e('Azores','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Atlantic/Bermuda" <?php selected( $value,'Atlantic/Bermuda');?> ><?php _e('Bermuda','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Atlantic/Canary" <?php selected( $value,'Atlantic/Canary');?> ><?php _e('Canary','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Atlantic/Cape_Verde" <?php selected( $value,'Atlantic/Cape Verde');?> ><?php _e('Cape Verde','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Atlantic/Faroe" <?php selected( $value,'Atlantic/Faroe');?> ><?php _e('Faroe','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Atlantic/Madeira" <?php selected( $value,'Atlantic/Madeira');?> ><?php _e('Madeira','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Atlantic/Reykjavik" <?php selected( $value,'Atlantic/Reykjavik');?> ><?php _e('Reykjavik','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Atlantic/South_Georgia" <?php selected( $value,'Atlantic/South Georgia');?> ><?php _e('South Georgia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Atlantic/Stanley" <?php selected( $value,'Atlantic/Stanley');?> ><?php _e('Stanley','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Atlantic/St_Helena" <?php selected( $value,'Atlantic/St Helena');?> ><?php _e('St Helena','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="Australia">
<option value="Australia/Adelaide" <?php selected( $value,'Australia/Adelaide');?> ><?php _e('Adelaide','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Brisbane" <?php selected( $value,'Australia/Brisbane');?> ><?php _e('Brisbane','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Broken_Hill" <?php selected( $value,'Australia/Broken Hill');?> ><?php _e('Broken Hill','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Currie" <?php selected( $value,'Australia/Currie');?> ><?php _e('Currie','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Darwin" <?php selected( $value,'Australia/Darwin');?> ><?php _e('Darwin','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Eucla" <?php selected( $value,'Australia/Eucla');?> ><?php _e('Eucla','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Hobart" <?php selected( $value,'Australia/Hobart');?> ><?php _e('Hobart','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Lindeman" <?php selected( $value,'Australia/Lindeman');?> ><?php _e('Lindeman','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Lord_Howe" <?php selected( $value,'Australia/Windhoek');?> ><?php _e('Lord Howe','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Melbourne" <?php selected( $value,'Australia/Melbourne');?> ><?php _e('Melbourne','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Perth" <?php selected( $value,'Australia/Perth');?> ><?php _e('Perth','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Australia/Sydney" <?php selected( $value,'Australia/Sydney');?> ><?php _e('Sydney','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="Europe" >
<option value="Europe/Amsterdam" <?php selected( $value,'Europe/Amsterdam');?> ><?php _e('Amsterdam','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Andorra" <?php selected( $value,'Europe/Andorra');?> ><?php _e('Andorra','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Athens" <?php selected( $value,'Europe/Athens');?> ><?php _e('Athens','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Belgrade" <?php selected( $value,'Europe/Belgrade');?> ><?php _e('Belgrade','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Berlin" <?php selected( $value,'Europe/Berlin');?> ><?php _e('Berlin','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Bratislava" <?php selected( $value,'Europe/Bratislava');?> ><?php _e('Bratislava','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Brussels" <?php selected( $value,'Europe/Brussels');?> ><?php _e('Brussels','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Bucharest" <?php selected( $value,'Europe/Bucharest');?> ><?php _e('Bucharest','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Budapest" <?php selected( $value,'Europe/Budapest');?> ><?php _e('Budapest','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Busingen" <?php selected( $value,'Europe/Busingen');?> ><?php _e('Busingen','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Chisinau" <?php selected( $value,'Europe/Chisinau');?> ><?php _e('Chisinau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Copenhagen" <?php selected( $value,'Europe/Copenhagen');?> ><?php _e('Copenhagen','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Dublin" <?php selected( $value,'Europe/Dublin');?> ><?php _e('Dublin','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Gibraltar" <?php selected( $value,'Europe/Gibraltar');?> ><?php _e('Gibraltar','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Guernsey" <?php selected( $value,'Europe/Guernsey');?> ><?php _e('Guernsey','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Helsinki" <?php selected( $value,'Europe/Helsinki');?> ><?php _e('Helsinki','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Isle_of_Man" <?php selected( $value,'Europe/Isle of Man');?> ><?php _e('Isle of Man','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Istanbul" <?php selected( $value,'Europe/Istanbul');?> ><?php _e('Istanbul','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Jersey" <?php selected( $value,'Europe/Jersey');?> ><?php _e('Jersey','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Kaliningrad" <?php selected( $value,'Europe/Kaliningrad');?> ><?php _e('Kaliningrad','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Kiev" <?php selected( $value,'Europe/Kiev');?> ><?php _e('Kiev','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Lisbon" <?php selected( $value,'Europe/Lisbon');?> ><?php _e('Lisbon','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Ljubljana" <?php selected( $value,'Europe/Ljubljana');?> ><?php _e('Ljubljana','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/London" <?php selected( $value,'Europe/London');?> ><?php _e('London','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Luxembourg" <?php selected( $value,'Europe/Luxembourg');?> ><?php _e('Luxembourg','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Madrid" <?php selected( $value,'Europe/Madrid');?> ><?php _e('Madrid','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Malta" <?php selected( $value,'Europe/Malta');?> ><?php _e('Malta','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Mariehamn" <?php selected( $value,'Europe/Mariehamn');?> ><?php _e('Mariehamn','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Minsk" <?php selected( $value,'Europe/Minsk');?> ><?php _e('Minsk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Monaco" <?php selected( $value,'Europe/Monaco');?> ><?php _e('Monaco','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Moscow" <?php selected( $value,'Europe/Moscow');?> ><?php _e('Moscow','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Oslo" <?php selected( $value,'Europe/Oslo');?> ><?php _e('Oslo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Paris" <?php selected( $value,'Europe/Paris');?> ><?php _e('Paris','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Podgorica" <?php selected( $value,'Europe/Podgorica');?> ><?php _e('Podgorica','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Prague" <?php selected( $value,'Europe/Prague');?> ><?php _e('Prague','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Riga" <?php selected( $value,'Europe/Riga');?> ><?php _e('Riga','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Rome" <?php selected( $value,'Europe/Rome');?> ><?php _e('Rome','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Samara" <?php selected( $value,'Europe/Samara');?> ><?php _e('Samara','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/San_Marino" <?php selected( $value,'Europe/San Marino');?> ><?php _e('San Marino','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Sarajevo" <?php selected( $value,'Europe/Sarajevo');?> ><?php _e('Sarajevo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Simferopol" <?php selected( $value,'Europe/Simferopol');?> ><?php _e('Simferopol','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Skopje" <?php selected( $value,'Europe/Skopje');?> ><?php _e('Skopje','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Sofia" <?php selected( $value,'Europe/Sofia');?> ><?php _e('Sofia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Stockholm" <?php selected( $value,'Europe/Stockholm');?> ><?php _e('Stockholm','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Tallinn" <?php selected( $value,'Europe/Tallinn');?> ><?php _e('Tallinn','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Tirane" <?php selected( $value,'Europe/Tirane');?> ><?php _e('Tirane','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Uzhgorod" <?php selected( $value,'Europe/Uzhgorod');?> ><?php _e('Uzhgorod','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Vaduz" <?php selected( $value,'Europe/Vaduz');?> ><?php _e('Vaduz','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Vatican" <?php selected( $value,'Europe/Vatican');?> ><?php _e('Vatican','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Vienna" <?php selected( $value,'Europe/Vienna');?> ><?php _e('Vienna','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Vilnius" <?php selected( $value,'Europe/Vilnius');?> ><?php _e('Vilnius','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Volgograd" <?php selected( $value,'Europe/Volgograd');?> ><?php _e('Volgograd','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Warsaw" <?php selected( $value,'Europe/Warsaw');?> ><?php _e('Warsaw','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Zagreb" <?php selected( $value,'Europe/Zagreb');?> ><?php _e('Zagreb','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Zaporozhye" <?php selected( $value,'Europe/Zaporozhye');?> ><?php _e('Zaporozhye','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Europe/Zurich" <?php selected( $value,'Europe/Zurich');?> ><?php _e('Zurich','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="Indian" >
<option value="Indian/Antananarivo" <?php selected( $value,'Indian/Antananarivo');?> ><?php _e('Antananarivo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Chagos" <?php selected( $value,'Indian/Chagos');?> ><?php _e('Chagos','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Christmas" <?php selected( $value,'Indian/Christmas');?> ><?php _e('Christmas','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Cocos" <?php selected( $value,'Indian/Cocos');?> ><?php _e('Cocos','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Comoro" <?php selected( $value,'Indian/Comoro');?> ><?php _e('Comoro','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Kerguelen" <?php selected( $value,'Indian/Kerguelen');?> ><?php _e('Kerguelen','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Mahe" <?php selected( $value,'Indian/Mahe');?> ><?php _e('Mahe','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Maldives" <?php selected( $value,'Indian/Maldives');?> ><?php _e('Maldives','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Mauritius" <?php selected( $value,'Indian/Mauritius');?> ><?php _e('Mauritius','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Mayotte" <?php selected( $value,'Indian/Mayotte');?> ><?php _e('Mayotte','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Indian/Reunion" <?php selected( $value,'Indian/Reunion');?> ><?php _e('Reunion','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="Pacific" >
<option value="Pacific/Apia" <?php selected( $value,'Pacific/Apia');?> ><?php _e('Apia','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Auckland" <?php selected( $value,'Pacific/Auckland');?> ><?php _e('Auckland','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Chatham" <?php selected( $value,'Pacific/Chatham');?> ><?php _e('Chatham','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Chuuk" <?php selected( $value,'Pacific/Chuuk');?> ><?php _e('Chuuk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Easter" <?php selected( $value,'Pacific/Easter');?> ><?php _e('Easter','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Efate" <?php selected( $value,'Pacific/Efate');?> ><?php _e('Efate','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Enderbury" <?php selected( $value,'Pacific/Enderbury');?> ><?php _e('Enderbury','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Fakaofo" <?php selected( $value,'Pacific/Fakaofo');?> ><?php _e('Fakaofo','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Fiji" <?php selected( $value,'Pacific/Fiji');?> ><?php _e('Fiji','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Funafuti" <?php selected( $value,'Pacific/Funafuti');?> ><?php _e('Funafuti','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Galapagos" <?php selected( $value,'Pacific/Galapagos');?> ><?php _e('Galapagos','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Gambier" <?php selected( $value,'Pacific/Gambier');?> ><?php _e('Gambier','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Guadalcanal" <?php selected( $value,'Pacific/Guadalcanal');?> ><?php _e('Guadalcanal','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Guam" <?php selected( $value,'Pacific/Guam');?> ><?php _e('Guam','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Honolulu" <?php selected( $value,'Pacific/Honolulu');?> ><?php _e('Honolulu','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Johnston" <?php selected( $value,'Pacific/Johnston');?> ><?php _e('Johnston','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Kiritimati" <?php selected( $value,'Pacific/Kiritimati');?> ><?php _e('Kiritimati','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Kosrae" <?php selected( $value,'Pacific/Kosrae');?> ><?php _e('Kosrae','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Kwajalein" <?php selected( $value,'Pacific/Kwajalein');?> ><?php _e('Kwajalein','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Majuro" <?php selected( $value,'Pacific/Majuro');?> ><?php _e('Majuro','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Marquesas" <?php selected( $value,'Pacific/Marquesas');?> ><?php _e('Marquesas','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Midway" <?php selected( $value,'Pacific/Midway');?> ><?php _e('Midway','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Nauru" <?php selected( $value,'Pacific/Nauru');?> ><?php _e('Nauru','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Niue" <?php selected( $value,'Pacific/Niue');?> ><?php _e('Niue','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Norfolk" <?php selected( $value,'Pacific/Norfolk');?> ><?php _e('Norfolk','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Noumea" <?php selected( $value,'Pacific/Noumea');?> ><?php _e('Noumea','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Pago_Pago" <?php selected( $value,'Pacific/Pago Pago');?> ><?php _e('Pago Pago','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Palau" <?php selected( $value,'Pacific/Palau');?> ><?php _e('Palau','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Pitcairn" <?php selected( $value,'Pacific/Pitcairn');?> ><?php _e('Pitcairn','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Pohnpei" <?php selected( $value,'Pacific/Pohnpei');?> ><?php _e('Pohnpei','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Port_Moresby" <?php selected( $value,'Pacific/Port Moresby');?> ><?php _e('Port Moresby','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Rarotonga" <?php selected( $value,'Pacific/Rarotonga');?> ><?php _e('Rarotonga','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Saipan" <?php selected( $value,'Pacific/Saipan');?> ><?php _e('Saipan','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Tahiti" <?php selected( $value,'Pacific/Tahiti');?> ><?php _e('Tahiti','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Tarawa" <?php selected( $value,'Pacific/Tarawa');?> ><?php _e('Tarawa','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Tongatapu" <?php selected( $value,'Pacific/Tongatapu');?> ><?php _e('Tongatapu','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Wake" <?php selected( $value,'Pacific/Wake');?> ><?php _e('Wake','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="Pacific/Wallis" <?php selected( $value,'Pacific/Wallis');?> ><?php _e('Wallis','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="UTC" >
<option value="UTC" <?php selected( $value,'UTC');?> ><?php _e('UTC','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>
<optgroup label="Manual Offsets">
<option value="UTC-12" <?php selected( $value,'UTC-12');?> ><?php _e('UTC-12','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-11.5" <?php selected( $value,'UTC-11:30');?> ><?php _e('UTC-11:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-11" <?php selected( $value,'UTC-11');?> ><?php _e('UTC-11','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-10.5" <?php selected( $value,'UTC-10:30');?> ><?php _e('UTC-10:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-10" <?php selected( $value,'UTC-10');?> ><?php _e('UTC-10','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-9.5" <?php selected( $value,'UTC-9:30');?> ><?php _e('UTC-9:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-9" <?php selected( $value,'UTC-9');?> ><?php _e('UTC-9','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-8.5" <?php selected( $value,'UTC-8:30');?> ><?php _e('UTC-8:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-8" <?php selected( $value,'UTC-8');?> ><?php _e('UTC-8','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-7.5" <?php selected( $value,'UTC-7:30');?> ><?php _e('UTC-7:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-7" <?php selected( $value,'UTC-7');?> ><?php _e('UTC-7','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-6.5" <?php selected( $value,'UTC-6:30');?> ><?php _e('UTC-6:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-6" <?php selected( $value,'UTC-6');?> ><?php _e('UTC-6','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-5.5" <?php selected( $value,'UTC-5:30');?> ><?php _e('UTC-5:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-5" <?php selected( $value,'UTC-5');?> ><?php _e('UTC-5','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-4.5" <?php selected( $value,'UTC-4:30');?> ><?php _e('UTC-4:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-4" <?php selected( $value,'UTC-4');?> ><?php _e('UTC-4','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-3.5" <?php selected( $value,'UTC-3:30');?> ><?php _e('UTC-3:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-3" <?php selected( $value,'UTC-3');?> ><?php _e('UTC-3','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-2.5" <?php selected( $value,'UTC-2:30');?> ><?php _e('UTC-2:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-2" <?php selected( $value,'UTC-2');?> ><?php _e('UTC-2','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-1.5" <?php selected( $value,'UTC-1:30');?> ><?php _e('UTC-1:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-1" <?php selected( $value,'UTC-1');?> ><?php _e('UTC-1','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC-0.5" <?php selected( $value,'UTC-0:30');?> ><?php _e('UTC-0:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+0" <?php selected( $value,'UTC+0');?> ><?php _e('UTC+0','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+0.5" <?php selected( $value,'UTC+0:30');?> ><?php _e('UTC+0:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+1" <?php selected( $value,'UTC+1');?> ><?php _e('UTC+1','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+1.5" <?php selected( $value,'UTC+1:30');?> ><?php _e('UTC+1:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+2" <?php selected( $value,'UTC+2');?> ><?php _e('UTC+2','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+2.5" <?php selected( $value,'UTC+2:30');?> ><?php _e('UTC+2:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+3" <?php selected( $value,'UTC+3');?> ><?php _e('UTC+3','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+3.5" <?php selected( $value,'UTC+3:30');?> ><?php _e('UTC+3:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+4" <?php selected( $value,'UTC+4');?> ><?php _e('UTC+4','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+4.5" <?php selected( $value,'UTC+4:30');?> ><?php _e('UTC+4:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+5" <?php selected( $value,'UTC+5');?> ><?php _e('UTC+5','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+5.5" <?php selected( $value,'UTC+5:30');?> ><?php _e('UTC+5:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+5.75" <?php selected( $value,'UTC+5:45');?> ><?php _e('UTC+5:45','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+6" <?php selected( $value,'UTC+6');?> ><?php _e('UTC+6','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+6.5" <?php selected( $value,'UTC+6:30');?> ><?php _e('UTC+6:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+7" <?php selected( $value,'UTC+7');?> ><?php _e('UTC+7','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+7.5" <?php selected( $value,'UTC+7:30');?> ><?php _e('UTC+7:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+8" <?php selected( $value,'UTC+8');?> ><?php _e('UTC+8','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+8.5" <?php selected( $value,'UTC+8:30');?> ><?php _e('UTC+8:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+8.75" <?php selected( $value,'UTC+8:45');?> ><?php _e('UTC+8:45','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+9" <?php selected( $value,'UTC+9');?> ><?php _e('UTC+9','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+9.5" <?php selected( $value,'UTC+9:30');?> ><?php _e('UTC+9:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+10" <?php selected( $value,'UTC+10');?> ><?php _e('UTC+10','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+10.5" <?php selected( $value,'UTC+10:30');?> ><?php _e('UTC+10:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+11" <?php selected( $value,'UTC+11');?> ><?php _e('UTC+11','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+11.5" <?php selected( $value,'UTC+11:30');?> ><?php _e('UTC+11:30','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+12" <?php selected( $value,'UTC+12');?> ><?php _e('UTC+12','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+12.75" <?php selected( $value,'UTC+12:45');?> ><?php _e('UTC+12:45','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+13" <?php selected( $value,'UTC+13');?> ><?php _e('UTC+13','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+13.75" <?php selected( $value,'UTC+13:45');?> ><?php _e('UTC+13:45','profilegrid-user-profiles-groups-and-communities');?></option>
<option value="UTC+14" <?php selected( $value,'UTC+14');?> ><?php _e('>UTC+14','profilegrid-user-profiles-groups-and-communities');?></option>
</optgroup>